# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release-Build

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Build with Maven
        run: echo building ${{github.ref_name}} && export BUILD_NUMBER=${{github.ref_name}} ; mvn -B package --file pom.xml
      
      - name: Upload Release      
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/dependencies.jar*
          token: ${{ secrets.GITHUB_TOKEN }}

    